### ISSUE TITLE
Atualizar README, prevendo a necessidade de atualização do angular

### ISSUE THREAD

**Issue by Canellas** [ONSBR/Plataforma-PresentationApp#2]
Para resolver a situação:

![image](https://user-images.githubusercontent.com/4662944/34413931-921cce1c-ebcd-11e7-811d-4eab4bcbf354.png)

É necessário executar ```npm install -g @angular/cli@latest```, para poder depois executar ```ng serve -o```

**Comment by jeanesaldanha** [comment]
Issue migrada para Done em 23/05/2018.
